# Copyright © 2024–2026 rzrn

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

all clean nuke download game chksum depend printenv:
	@touch build/prerequisites.mk
	@. build/configure.sh && $(MAKE) -f build/prerequisites.mk -f build/flags.mk -f build/rules.mk $@

help:
	@echo "Usage: [VAR1=VALUE1] [VAR2=VALUE2] ... make [VAR3=VALUE3] ... [TARGET]"
	@echo ""
	@echo "Note that ‘make VAR=VALUE [TARGET]’ may produce results you don’t expect."
	@echo "In most cases, you place variables specified in ‘build/configure.mk’ before"
	@echo "the ‘make’ command, and variables specified in ‘build/flags.mk’ after it."
	@echo ""
	@echo "If you don’t know what target to use, ‘TOOLKIT=GLFW make game’ is most"
	@echo "likely what you need."
	@echo ""
	@echo "Targets:"
	@echo "  all          Build the game binary only."
	@echo "               NB: this target DOES NOT prepare the game distribution."
	@echo "  clean        Clean up object files located in the ‘src/’ directory."
	@echo "  nuke         Clean up object files both in ‘src/’ and ‘vendor/’ directories."
	@echo "  download     Download game resources."
	@echo "  game         Prepare the game distribution."
	@echo "               NB: this target may use an internet connection to download game"
	@echo "               resources."
	@echo "  chksum       Verify checksum using a specified $HASHPROG tool."
	@echo "  depend       Run ‘makedepend’ to generate dependency tree. Useful for"
	@echo "               developers."
	@echo "  printenv     Print flags exported by the ‘build/configure.sh’ script for"
	@echo "               your reference."
	@echo "  help         Display this message."
	@echo ""
	@echo "Variables specified in ‘build/configure.mk’:"
	@echo "  PLATFORM     One of these: NT, Linux, Mac, FreeBSD, Haiku."
	@echo "               By default, it is selected based on the output of"
	@echo "               the ‘uname’ command."
	@echo "  PROFILE      Either ‘RELEASE’ or ‘DEBUG’."
	@echo "  COMMITHASH   A short git commit hash shown in the game interface."
	@echo "               By default, it is generated automatically but may be overridden"
	@echo "               for custom builds."
	@echo "  TOOLKIT      One of these: SDL, GLFW, GLUT, Cocoa."
	@echo "  OPTLEVEL     The level of code optimization passed to the compiler when"
	@echo "               the ‘RELEASE’ profile is selected."
	@echo "  CFLAGS1      Optional CFLAGS used to compile source files from"
	@echo "               the ‘src/’ subdirectory."
	@echo "  CFLAGS2      Optional CFLAGS used to compile source files from"
	@echo "               the ‘vendor/’ subdirectory."
	@echo "  LDFLAGS      Optional LDFLAGS used to link the game binary."
	@echo ""
	@echo "Variables specified in ‘build/flags.mk’:"
	@echo "  CC           C compiler command."
	@echo "  LD           Linker command."
	@echo "  RESDIR       Directory with game resources other than from $PACKFILE."
	@echo "  GAMEDIR      The game distribution directory."
	@echo "  EXEFILE      Name of the game binary."
	@echo "  PACKURL      URL where game resources are available."
	@echo "  PACKFILE     Path to the file with game resources."
	@echo "  HASHPROG     Command used to verify the hash of the archive with game"
	@echo "               resources."
	@echo ""
	@echo "To inspect the relevant environment variables generated by"
	@echo "the ‘build/configure.sh’ script, use"
	@echo "  VAR1=VALUE1 <...> make VAR2=VALUE2 <...> printenv"
	@echo "Note that CFLAGS passed as ‘CFLAGS1=<...> make <...>’ are appended to"
	@echo "the other parameters generated by the ‘build/configure.sh’ script. If you"
	@echo "want to override these parameters instead, you can either pass them as"
	@echo "  make CFLAGS1=<...> <...>"
	@echo "or consider the manual invocation like this:"
	@echo "  make -f build/prerequisites.mk -f build/flags.mk -f build/rules.mk\\"
	@echo "       CFLAGS1=<...> CFLAGS2=<...> <...>"
	@echo "which you can place in your custom build script."
