#define TOOLKIT "Cocoa"

#define COCOA_SPECIAL_MASK       (1 << 30)
#define COCOA_KEY_SHIFT          COCOA_SPECIAL_MASK | 1
#define COCOA_KEY_CONTROL        COCOA_SPECIAL_MASK | 2
#define COCOA_KEY_ALT            COCOA_SPECIAL_MASK | 3

#define TOOLKIT_KEY_SPACE        65
#define TOOLKIT_KEY_SHIFT        COCOA_KEY_SHIFT
#define TOOLKIT_KEY_CONTROL      COCOA_KEY_CONTROL
#define TOOLKIT_KEY_CURSOR_UP    111
#define TOOLKIT_KEY_CURSOR_DOWN  116
#define TOOLKIT_KEY_CURSOR_LEFT  113
#define TOOLKIT_KEY_CURSOR_RIGHT 114
#define TOOLKIT_KEY_BACKSPACE    22
#define TOOLKIT_KEY_TAB          23
#define TOOLKIT_KEY_ESCAPE       9
#define TOOLKIT_KEY_ENTER        36
#define TOOLKIT_KEY_A            38
#define TOOLKIT_KEY_B            56
#define TOOLKIT_KEY_C            54
#define TOOLKIT_KEY_D            40
#define TOOLKIT_KEY_E            26
#define TOOLKIT_KEY_F            41
#define TOOLKIT_KEY_G            42
#define TOOLKIT_KEY_H            43
#define TOOLKIT_KEY_I            31
#define TOOLKIT_KEY_J            44
#define TOOLKIT_KEY_K            45
#define TOOLKIT_KEY_L            46
#define TOOLKIT_KEY_M            58
#define TOOLKIT_KEY_N            57
#define TOOLKIT_KEY_O            32
#define TOOLKIT_KEY_P            33
#define TOOLKIT_KEY_Q            24
#define TOOLKIT_KEY_R            27
#define TOOLKIT_KEY_S            39
#define TOOLKIT_KEY_T            28
#define TOOLKIT_KEY_U            30
#define TOOLKIT_KEY_V            55
#define TOOLKIT_KEY_W            25
#define TOOLKIT_KEY_X            53
#define TOOLKIT_KEY_Y            29
#define TOOLKIT_KEY_Z            52
#define TOOLKIT_KEY_1            10
#define TOOLKIT_KEY_2            11
#define TOOLKIT_KEY_3            12
#define TOOLKIT_KEY_4            13
#define TOOLKIT_KEY_5            14
#define TOOLKIT_KEY_6            15
#define TOOLKIT_KEY_7            16
#define TOOLKIT_KEY_8            17
#define TOOLKIT_KEY_9            18
#define TOOLKIT_KEY_0            19
#define TOOLKIT_KEY_F1           67
#define TOOLKIT_KEY_F2           68
#define TOOLKIT_KEY_F3           69
#define TOOLKIT_KEY_F4           70
#define TOOLKIT_KEY_F5           71
#define TOOLKIT_KEY_F6           72
#define TOOLKIT_KEY_F7           73
#define TOOLKIT_KEY_F8           74
#define TOOLKIT_KEY_F9           75
#define TOOLKIT_KEY_F10          76
#define TOOLKIT_KEY_F11          95
#define TOOLKIT_KEY_F12          96
#define TOOLKIT_KEY_ADD          86
#define TOOLKIT_KEY_SUBTRACT     82
#define TOOLKIT_KEY_COMMA        59
#define TOOLKIT_KEY_PERIOD       60
#define TOOLKIT_KEY_SLASH        61
