#define TOOLKIT "GLFW"

#define TOOLKIT_KEY_SPACE        GLFW_KEY_SPACE
#define TOOLKIT_KEY_SHIFT        GLFW_KEY_LEFT_SHIFT
#define TOOLKIT_KEY_CONTROL      GLFW_KEY_LEFT_CONTROL
#define TOOLKIT_KEY_CURSOR_UP    GLFW_KEY_UP
#define TOOLKIT_KEY_CURSOR_DOWN  GLFW_KEY_DOWN
#define TOOLKIT_KEY_CURSOR_LEFT  GLFW_KEY_LEFT
#define TOOLKIT_KEY_CURSOR_RIGHT GLFW_KEY_RIGHT
#define TOOLKIT_KEY_BACKSPACE    GLFW_KEY_BACKSPACE
#define TOOLKIT_KEY_TAB          GLFW_KEY_TAB
#define TOOLKIT_KEY_ESCAPE       GLFW_KEY_ESCAPE
#define TOOLKIT_KEY_ENTER        GLFW_KEY_ENTER
#define TOOLKIT_KEY_A            GLFW_KEY_A
#define TOOLKIT_KEY_B            GLFW_KEY_B
#define TOOLKIT_KEY_C            GLFW_KEY_C
#define TOOLKIT_KEY_D            GLFW_KEY_D
#define TOOLKIT_KEY_E            GLFW_KEY_E
#define TOOLKIT_KEY_F            GLFW_KEY_F
#define TOOLKIT_KEY_G            GLFW_KEY_G
#define TOOLKIT_KEY_H            GLFW_KEY_H
#define TOOLKIT_KEY_I            GLFW_KEY_I
#define TOOLKIT_KEY_J            GLFW_KEY_J
#define TOOLKIT_KEY_K            GLFW_KEY_K
#define TOOLKIT_KEY_L            GLFW_KEY_L
#define TOOLKIT_KEY_M            GLFW_KEY_M
#define TOOLKIT_KEY_N            GLFW_KEY_N
#define TOOLKIT_KEY_O            GLFW_KEY_O
#define TOOLKIT_KEY_P            GLFW_KEY_P
#define TOOLKIT_KEY_Q            GLFW_KEY_Q
#define TOOLKIT_KEY_R            GLFW_KEY_R
#define TOOLKIT_KEY_S            GLFW_KEY_S
#define TOOLKIT_KEY_T            GLFW_KEY_T
#define TOOLKIT_KEY_U            GLFW_KEY_U
#define TOOLKIT_KEY_V            GLFW_KEY_V
#define TOOLKIT_KEY_W            GLFW_KEY_W
#define TOOLKIT_KEY_X            GLFW_KEY_X
#define TOOLKIT_KEY_Y            GLFW_KEY_Y
#define TOOLKIT_KEY_Z            GLFW_KEY_Z
#define TOOLKIT_KEY_1            GLFW_KEY_1
#define TOOLKIT_KEY_2            GLFW_KEY_2
#define TOOLKIT_KEY_3            GLFW_KEY_3
#define TOOLKIT_KEY_4            GLFW_KEY_4
#define TOOLKIT_KEY_5            GLFW_KEY_5
#define TOOLKIT_KEY_6            GLFW_KEY_6
#define TOOLKIT_KEY_7            GLFW_KEY_7
#define TOOLKIT_KEY_8            GLFW_KEY_8
#define TOOLKIT_KEY_9            GLFW_KEY_9
#define TOOLKIT_KEY_0            GLFW_KEY_0
#define TOOLKIT_KEY_F1           GLFW_KEY_F1
#define TOOLKIT_KEY_F2           GLFW_KEY_F2
#define TOOLKIT_KEY_F3           GLFW_KEY_F3
#define TOOLKIT_KEY_F4           GLFW_KEY_F4
#define TOOLKIT_KEY_F5           GLFW_KEY_F5
#define TOOLKIT_KEY_F6           GLFW_KEY_F6
#define TOOLKIT_KEY_F7           GLFW_KEY_F7
#define TOOLKIT_KEY_F8           GLFW_KEY_F8
#define TOOLKIT_KEY_F9           GLFW_KEY_F9
#define TOOLKIT_KEY_F10          GLFW_KEY_F10
#define TOOLKIT_KEY_F11          GLFW_KEY_F11
#define TOOLKIT_KEY_F12          GLFW_KEY_F12
#define TOOLKIT_KEY_ADD          GLFW_KEY_KP_ADD
#define TOOLKIT_KEY_SUBTRACT     GLFW_KEY_KP_SUBTRACT
#define TOOLKIT_KEY_COMMA        GLFW_KEY_COMMA
#define TOOLKIT_KEY_PERIOD       GLFW_KEY_PERIOD
#define TOOLKIT_KEY_SLASH        GLFW_KEY_SLASH
