#define TOOLKIT "SDL"

#define TOOLKIT_KEY_SPACE        SDLK_SPACE
#define TOOLKIT_KEY_SHIFT        SDLK_LSHIFT
#define TOOLKIT_KEY_CONTROL      SDLK_LCTRL
#define TOOLKIT_KEY_CURSOR_UP    SDLK_UP
#define TOOLKIT_KEY_CURSOR_DOWN  SDLK_DOWN
#define TOOLKIT_KEY_CURSOR_LEFT  SDLK_LEFT
#define TOOLKIT_KEY_CURSOR_RIGHT SDLK_RIGHT
#define TOOLKIT_KEY_BACKSPACE    SDLK_BACKSPACE
#define TOOLKIT_KEY_TAB          SDLK_TAB
#define TOOLKIT_KEY_ESCAPE       SDLK_ESCAPE
#define TOOLKIT_KEY_ENTER        SDLK_RETURN
#define TOOLKIT_KEY_A            SDLK_a
#define TOOLKIT_KEY_B            SDLK_b
#define TOOLKIT_KEY_C            SDLK_c
#define TOOLKIT_KEY_D            SDLK_d
#define TOOLKIT_KEY_E            SDLK_e
#define TOOLKIT_KEY_F            SDLK_f
#define TOOLKIT_KEY_G            SDLK_g
#define TOOLKIT_KEY_H            SDLK_h
#define TOOLKIT_KEY_I            SDLK_i
#define TOOLKIT_KEY_J            SDLK_j
#define TOOLKIT_KEY_K            SDLK_k
#define TOOLKIT_KEY_L            SDLK_l
#define TOOLKIT_KEY_M            SDLK_m
#define TOOLKIT_KEY_N            SDLK_n
#define TOOLKIT_KEY_O            SDLK_o
#define TOOLKIT_KEY_P            SDLK_p
#define TOOLKIT_KEY_Q            SDLK_q
#define TOOLKIT_KEY_R            SDLK_r
#define TOOLKIT_KEY_S            SDLK_s
#define TOOLKIT_KEY_T            SDLK_t
#define TOOLKIT_KEY_U            SDLK_u
#define TOOLKIT_KEY_V            SDLK_v
#define TOOLKIT_KEY_W            SDLK_w
#define TOOLKIT_KEY_X            SDLK_x
#define TOOLKIT_KEY_Y            SDLK_y
#define TOOLKIT_KEY_Z            SDLK_z
#define TOOLKIT_KEY_1            SDLK_1
#define TOOLKIT_KEY_2            SDLK_2
#define TOOLKIT_KEY_3            SDLK_3
#define TOOLKIT_KEY_4            SDLK_4
#define TOOLKIT_KEY_5            SDLK_5
#define TOOLKIT_KEY_6            SDLK_6
#define TOOLKIT_KEY_7            SDLK_7
#define TOOLKIT_KEY_8            SDLK_8
#define TOOLKIT_KEY_9            SDLK_9
#define TOOLKIT_KEY_0            SDLK_0
#define TOOLKIT_KEY_F1           SDLK_F1
#define TOOLKIT_KEY_F2           SDLK_F2
#define TOOLKIT_KEY_F3           SDLK_F3
#define TOOLKIT_KEY_F4           SDLK_F4
#define TOOLKIT_KEY_F5           SDLK_F5
#define TOOLKIT_KEY_F6           SDLK_F6
#define TOOLKIT_KEY_F7           SDLK_F7
#define TOOLKIT_KEY_F8           SDLK_F8
#define TOOLKIT_KEY_F9           SDLK_F9
#define TOOLKIT_KEY_F10          SDLK_F10
#define TOOLKIT_KEY_F11          SDLK_F11
#define TOOLKIT_KEY_F12          SDLK_F12
#define TOOLKIT_KEY_ADD          SDLK_KP_PLUS
#define TOOLKIT_KEY_SUBTRACT     SDLK_KP_MINUS
#define TOOLKIT_KEY_COMMA        SDLK_COMMA
#define TOOLKIT_KEY_PERIOD       SDLK_PERIOD
#define TOOLKIT_KEY_SLASH        SDLK_SLASH
